### PR TITLE
Fix overlapping label for radio and range Materialize theme (fixes #205)

### LINKED ISSUE #205: Materialize Theme Glitches with Default Values & Range
### Expected behavior
Labels should not overlap form elements.

### Actual behavior
If a default value is specified for any type that evaluates to a text input (string, number, etc.), the label overlaps the input field when using the Materialize theme.  

This also applies when using the 'range' number format, even without a default value being specified.

### Analysis / Workaround
The 'active' class needs to be applied to the label any time a default value is specified, or if the format is specified as range.

As a workaround, executing M.updateTextFields() in the editor.on('ready') handler resolves the case when default values are specified.

And for the range elements (if using jquery):
  $('.input-field:has(.range-output) label').addClass('active')

The default behavior of the plugin should be fixed to handle these cases, though I'm not familiar enough with this plugin to figure out how to do so myself.

### PR DESCRIPTION
**Pull request by lukzas**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️ Good for 2.x
| Tests pass?   | Not run, shouldn't impact
| Fixed issues  | #205 

This is a partial fix for radio and range elements only. Tried to fix as generic as possible, added data-container-for attribute for element types wrapped in additional div, so that we know what's actually inside. This might be useful not only for Materialize theme in case some manipulation is needed in getFormControl() function.

### CODE REVIEW

**Comment by schmunk42** [comment]
We need to make the tests pass for 2.x

**Comment by lukzas** [comment]
@schmunk42 Tests indeed are not passing, but they seem to be existing in develop/2.x branch before, so no new issues were introduced into the branch by PR.

File: src/editors/radio.js [hunk 1]
```diff
@@ -55,6 +55,7 @@ JSONEditor.defaults.editors.radio = JSONEditor.defaults.editors.select.extend({
 
     var radioContainerWrapper = this.theme.getContainer();
     radioContainerWrapper.appendChild(this.radioContainer);
+    radioContainerWrapper.dataset.containerFor = 'radio';
```
Comment (pmk65) [inline src/editors/radio.js]: You don't need the dataset part anymore?

Comment (lukzas) [reply src/editors/radio.js]: Theoretically, I don't 😄 I'm trying to refactor radio, let's discuss in #205

**Comment by pmk65** [comment]
I think the reason the tests fail, is because I rewrote the functionality of the select editor and the ones that extend it, like: Select2 and Selectize.
Select2 and Selectize has an option called "tags" or "create" (different names, but same functionality), where it is possible to input a value not present in the select list.
The rewritten select editor allows setting values not present in the enum list if the correct option is set. and works with either manual input, or using `setValue`. When a value not present in the enum list, the select editor will add the new value to the session enum list.

File: src/editors/radio.js (hunk 1 above)
Comment (lukzas) [reply src/editors/radio.js]: Moved dataset part to afterInputReady()

File: src/editors/radio.js [hunk 2]
```diff
@@ -85,6 +85,11 @@ JSONEditor.defaults.editors.radio = JSONEditor.defaults.editors.select.extend({
     this.radioContainer.classList.add('readonly');
     this._super();
   },
+  afterInputReady: function() {
```
Comment (pmk65) [inline src/editors/radio.js]: You should call the parent editor `afterInputReady` instead of calling `self.theme.afterInputReady(self.input);` directly. That way any afterInput code from the parent class is also executed.
````javascript
 afterInputReady: function() {
    var self = this;
    self.input.dataset.containerFor = 'radio';
    self._super();
````

Comment (lukzas) [reply src/editors/radio.js]: Agreed, didn't notice that radio is extending select and not an editor.

Comment (pmk65) [reply src/editors/radio.js]: It works like this: radio class extends select class which extends the editor class.
So radio class inherits all functions from select class which then inherits all functions from editor class.
Calling `this._super()` calls the function from the parent class if you override it in your code.

It is much better to extend the class that matches the functionality, rather than the editor class.
Like the radio editor works with enum, similar to select. So by extending select, all the enum functionality from the prebuild/init functions is already available.

Comment (lukzas) [reply src/editors/radio.js]: Ok, I got rid of `afterInputReady` and we're back to the same codebase 😄

**Comment by schmunk42** [comment]
I'd really like to sort https://github.com/json-editor/json-editor/issues/462 out first

**Comment by pmk65** [comment]
@schmunk42 Looks like it passed tests now.

**Comment by schmunk42** [comment]
Thank you!
